"""add summary_text and quality_score

Revision ID: 0179eb8e1705
Revises: f259af705ecd
Create Date: 2026-08-04 10:18:16.218744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0179eb8e1705'
down_revision: Union[str, Sequence[str], None] = 'f259af705ecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('quality_score', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'quality_score')
    # ### end Alembic commands ###
