"""add upload sessions

Revision ID: 3e1fdbabb6f8
Revises: 20261007_invoice_id_index
Create Date: 2026-10-07 09:27:14.791818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1fdbabb6f8'
down_revision: Union[str, Sequence[str], None] = '20261007_invoice_id_index'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage_id', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_sessions_expires_at'), 'upload_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_upload_sessions_id'), 'upload_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_upload_sessions_owner_id'), 'upload_sessions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_upload_sessions_status'), 'upload_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_upload_sessions_storage_id'), 'upload_sessions', ['storage_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_sessions_storage_id'), table_name='upload_sessions')
    op.drop_index(op.f('ix_upload_sessions_status'), table_name='upload_sessions')
    op.drop_index(op.f('ix_upload_sessions_owner_id'), table_name='upload_sessions')
    op.drop_index(op.f('ix_upload_sessions_id'), table_name='upload_sessions')
    op.drop_index(op.f('ix_upload_sessions_expires_at'), table_name='upload_sessions')
    op.drop_table('upload_sessions')
    # ### end Alembic commands ###
