"""add chat sessions and messages

Revision ID: c2cdee296c8e
Revises: 0179eb8e1705
Create Date: 2026-08-20 05:53:17.924129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2cdee296c8e'
down_revision: Union[str, Sequence[str], None] = '0179eb8e1705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    unowned_datasets = bind.execute(
        sa.text("SELECT count(*) FROM datasets WHERE owner_id IS NULL")
    ).scalar_one()
    if unowned_datasets:
        raise RuntimeError(
            f"Cannot require datasets.owner_id: {unowned_datasets} existing "
            "dataset(s) have no owner. Assign each dataset to its verified "
            "owner, then rerun this migration; no owner will be guessed."
        )

    bind.execute(
        sa.text(
            "UPDATE datasets "
            "SET uploaded_at = CURRENT_TIMESTAMP "
            "WHERE uploaded_at IS NULL"
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.alter_column('datasets', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               existing_nullable=True,
               nullable=False)
    op.alter_column('datasets', 'owner_id',
               existing_type=sa.INTEGER(),
               existing_nullable=True,
               nullable=False)
    op.drop_constraint(op.f('datasets_owner_id_fkey'), 'datasets', type_='foreignkey')
    op.create_foreign_key(
        'fk_datasets_owner_id_users',
        'datasets',
        'users',
        ['owner_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_datasets_owner_id_users', 'datasets', type_='foreignkey')
    op.create_foreign_key(op.f('datasets_owner_id_fkey'), 'datasets', 'users', ['owner_id'], ['id'])
    op.alter_column('datasets', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('datasets', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
