"""add summary_text to analyses (legacy filename says quality_score)

Revision ID: f259af705ecd
Revises: c29672287d79
Create Date: 2026-07-31 17:26:23.960613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f259af705ecd'
down_revision: Union[str, Sequence[str], None] = 'c29672287d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add a non-null summary with a safe backfill for existing analyses."""
    op.add_column(
        "analyses",
        sa.Column(
            "summary_text",
            sa.Text(),
            nullable=False,
            server_default=sa.text("''"),
        ),
    )
    op.alter_column(
        "analyses",
        "summary_text",
        existing_type=sa.Text(),
        existing_nullable=False,
        server_default=None,
    )


def downgrade() -> None:
    """Remove the summary_text column."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'summary_text')
    # ### end Alembic commands ###
