"""describe change

Revision ID: f957ba39a00d
Revises: 3523d78a50b6
Create Date: 2026-07-26 10:00:52.748088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f957ba39a00d'
down_revision: Union[str, Sequence[str], None] = '3523d78a50b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('rows', sa.Integer(), nullable=False))
    op.add_column('datasets', sa.Column('columns', sa.Integer(), nullable=False))
    op.alter_column('datasets', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('datasets', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('datasets_owner_id_fkey'), 'datasets', type_='foreignkey')
    op.create_foreign_key(None, 'datasets', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'datasets', type_='foreignkey')
    op.create_foreign_key(op.f('datasets_owner_id_fkey'), 'datasets', 'users', ['owner_id'], ['id'])
    op.alter_column('datasets', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('datasets', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('datasets', 'columns')
    op.drop_column('datasets', 'rows')
    # ### end Alembic commands ###
